# Generated by Django 3.2 on 2021-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_agent_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='signature',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
