# Generated by Django 3.2 on 2021-07-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0003_auto_20210730_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='artgraphique',
            name='numero_inventaire',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='peinturesurbois',
            name='numero_inventaire',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='peinturesurtoile',
            name='numero_inventaire',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artgraphique',
            name='photo_face',
            field=models.ImageField(null=True, upload_to='photos_identification_art_graphique/'),
        ),
        migrations.AlterField(
            model_name='artgraphique',
            name='photo_revers',
            field=models.ImageField(null=True, upload_to='photos_identification_art_graphique/'),
        ),
        migrations.AlterField(
            model_name='peinturesurbois',
            name='photo_face',
            field=models.ImageField(null=True, upload_to='photos_identification_peinture_sur_bois'),
        ),
        migrations.AlterField(
            model_name='peinturesurbois',
            name='photo_revers',
            field=models.ImageField(null=True, upload_to='photos_identification_peinture_sur_bois'),
        ),
        migrations.AlterField(
            model_name='peinturesurtoile',
            name='photo_face',
            field=models.ImageField(null=True, upload_to='photos_identification_peinture_sur_toile'),
        ),
        migrations.AlterField(
            model_name='peinturesurtoile',
            name='photo_revers',
            field=models.ImageField(null=True, upload_to='photos_identification_peinture_sur_toile'),
        ),
    ]
