# Generated by Django 3.2 on 2021-08-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0008_auto_20210801_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artgraphique',
            name='epaisseur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='artgraphique',
            name='hauteur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='artgraphique',
            name='largeur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='peinturesurbois',
            name='epaisseur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='peinturesurbois',
            name='hauteur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='peinturesurbois',
            name='largeur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='peinturesurtoile',
            name='epaisseur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='peinturesurtoile',
            name='hauteur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='peinturesurtoile',
            name='largeur_avec_cadre',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
