# Generated by Django 3.2 on 2021-08-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0014_auto_20210805_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constatpeinturesurbois',
            name='peinture_sur_bois',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constat_d_etat.peinturesurbois'),
        ),
    ]
