# Generated by Django 3.2 on 2021-08-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0016_alter_constatpeinturesurbois_support_peinture_sur_bois'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photosignificativecouchepicturalepeinture',
            old_name='couchePicturale',
            new_name='couche_picturale',
        ),
        migrations.RenameField(
            model_name='photosignificativesupportpeinturesurbois',
            old_name='supportPeintureSurBois',
            new_name='support',
        ),
        migrations.AlterField(
            model_name='photosignificativechassispeinturesurtoile',
            name='nature_alteration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photosignificativechassispeinturesurtoile',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photosignificativechassispeinturesurtoile',
            name='photo_avec_emplacement',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photosignificativecouchepicturalepeinture',
            name='nature_alteration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photosignificativecouchepicturalepeinture',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photosignificativecouchepicturalepeinture',
            name='photo_avec_emplacement',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photosignificativesupportpeinturesurbois',
            name='nature_alteration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photosignificativesupportpeinturesurbois',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photosignificativesupportpeinturesurbois',
            name='photo_avec_emplacement',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PhotoSignificativeCouchePicturalePeintureSurToile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_alteration', models.CharField(max_length=255)),
                ('face', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='')),
                ('photo_avec_emplacement', models.ImageField(upload_to='')),
                ('couchePicturale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constat_d_etat.couchepicturalepeinture')),
            ],
        ),
    ]
