# Generated by Django 3.2 on 2021-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0018_auto_20210812_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='constatartgraphique',
            name='signature_auteur',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='constatpeinturesurbois',
            name='signature_auteur',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='constatpeinturesurtoile',
            name='signature_auteur',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
