# Generated by Django 3.2 on 2021-08-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0019_auto_20210815_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoSignificativeCouchePicturalePeintureSurToile',
        ),
    ]
