# Generated by Django 3.2 on 2021-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0020_delete_photosignificativecouchepicturalepeinturesurtoile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosignificativecadreoeuvre',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos_significatives_cadre'),
        ),
        migrations.AlterField(
            model_name='photosignificativecadreoeuvre',
            name='photo_avec_emplacement',
            field=models.ImageField(null=True, upload_to='photos_significatives_cadre'),
        ),
        migrations.AlterField(
            model_name='photosignificativechassispeinturesurtoile',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos_significatives_chassis'),
        ),
        migrations.AlterField(
            model_name='photosignificativechassispeinturesurtoile',
            name='photo_avec_emplacement',
            field=models.ImageField(null=True, upload_to='photos_significatives_chassis'),
        ),
        migrations.AlterField(
            model_name='photosignificativecouchepicturalepeinture',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos_significatives_couche_picturale'),
        ),
        migrations.AlterField(
            model_name='photosignificativecouchepicturalepeinture',
            name='photo_avec_emplacement',
            field=models.ImageField(null=True, upload_to='photos_significatives_couche_picturale'),
        ),
        migrations.AlterField(
            model_name='photosignificativesupportartgraphique',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos_significatives_support'),
        ),
        migrations.AlterField(
            model_name='photosignificativesupportartgraphique',
            name='photo_avec_emplacement',
            field=models.ImageField(null=True, upload_to='photos_significatives_support'),
        ),
        migrations.AlterField(
            model_name='photosignificativesupportpeinturesurbois',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos_significatives_support'),
        ),
        migrations.AlterField(
            model_name='photosignificativesupportpeinturesurbois',
            name='photo_avec_emplacement',
            field=models.ImageField(null=True, upload_to='photos_significatives_support'),
        ),
    ]
