# Generated by Django 3.2 on 2021-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_agent_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='signature',
            field=models.ImageField(null=True, upload_to='signatures'),
        ),
    ]
