# Generated by Django 3.2 on 2021-07-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0002_auto_20210730_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montageartgraphique',
            old_name='defaut_d_adhérance',
            new_name='defaut_d_adherance',
        ),
        migrations.RenameField(
            model_name='techniqueartgraphique',
            old_name='versnis_altere',
            new_name='vernis_altere',
        ),
        migrations.AddField(
            model_name='supportartgraphique',
            name='rouille',
            field=models.BooleanField(default=False),
        ),
    ]
