# Generated by Django 3.2 on 2021-08-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0005_auto_20210731_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportpeinturesurbois',
            old_name='Alterations',
            new_name='alterations',
        ),
    ]
