# Generated by Django 3.2 on 2021-08-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0010_auto_20210802_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiauxsupportartgraphique',
            name='intervalles_de_pontuseaux',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materiauxsupportartgraphique',
            name='intervalles_des_vergeures',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
