# Generated by Django 3.2 on 2021-08-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0011_auto_20210802_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alterationcadreoeuvre',
            old_name='decord_fragilise',
            new_name='decor_fragilise',
        ),
        migrations.RenameField(
            model_name='caracteristiquescadreoeuvre',
            old_name='Feuillure_garnie_de_feutrine',
            new_name='feuillure_garnie_de_feutrine',
        ),
        migrations.RenameField(
            model_name='caracteristiquescadreoeuvre',
            old_name='Tampons_de_calage',
            new_name='tampons_de_calage',
        ),
        migrations.RenameField(
            model_name='systemedaccrochagecadreoeuvre',
            old_name='nombre_prete',
            new_name='nombre_pretee',
        ),
        migrations.RenameField(
            model_name='techniquedesseinartgraphique',
            old_name='autre_techniqueDessein',
            new_name='autre_technique_dessin',
        ),
        migrations.RenameField(
            model_name='techniqueestampeartgraphique',
            old_name='technique_combinees_techniqueEstampe',
            new_name='technique_combinees_technique_estampe',
        ),
    ]
