# Generated by Django 3.2 on 2021-08-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0013_auto_20210805_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constatpeinturesurbois',
            old_name='supportPeintureSurBois',
            new_name='support_peinture_sur_bois',
        ),
        migrations.RenameField(
            model_name='constatpeinturesurtoile',
            old_name='supportPeintureSurToile',
            new_name='support_peinture_sur_toile',
        ),
    ]
