# Generated by Django 3.2 on 2021-08-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constat_d_etat', '0015_alter_constatpeinturesurbois_peinture_sur_bois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constatpeinturesurbois',
            name='support_peinture_sur_bois',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constat_d_etat.supportpeinturesurbois'),
        ),
    ]
